repos:
  - repo: local
    hooks:
      - id: fmt
        name: format check
        entry: npm run fmt:check
        language: system
        pass_filenames: false
      - id: lint
        name: lint
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: build
        name: build
        entry: npm run build
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: npm run test:coverage
        language: system
        pass_filenames: false
